version: "3.8"
services:
  elasticsearch-search:
    image: elasticsearch:7.9.2
    environment:
      - discovery.type=single-node
#      - http.cors.enabled=true
#      - http.cors.allow-origin=*
#      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
#      - http.cors.allow-credentials=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx2048m -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    ports:
      - 9200:9200
      - 9300:9300
      - 5005:5005
    volumes:
      - /Volumes/my_passport/.jdata_elastic:/usr/share/elasticsearch/data
      - ./elastic_config/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml